version: 2.1

jobs:
  Ecal:
    docker:
      - image: koichimurakamik6/geant4-runtime:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: default
          docker_layer_caching: true
      - run:
          name: test_ecal
          command: |
            ./configure --with-geant4-dir=/opt/geant4 --disable-vis
            cd build/ecal
            make -j4
            ./ecal 10000
      - store_artifacts:
          path: ./build/ecal/g4bench.json

  Hcal:
    docker:
      - image: koichimurakamik6/geant4-runtime:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: test_hcal
          command: |
            ./configure --with-geant4-dir=/opt/geant4 --disable-vis
            cd build/hcal
            make -j4
            ./hcal 2000
      - store_artifacts:
          path: ./build/hcal/g4bench.json

  Vgeo:
    docker:
      - image: koichimurakamik6/geant4-runtime:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: test_vgeo
          command: |
            ./configure --with-geant4-dir=/opt/geant4 --disable-vis
            cd build/vgeo
            make -j4
            ./vgeo 100000
      - store_artifacts:
          path: ./build/vgeo/g4bench.json


workflows:
  Build_and_Run_Docker:
    jobs:
      - Ecal
      - Hcal
      - Vgeo
